name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version}}
      - uses: cypress-io/github-action@v4
        with:
          browser: electron
